[package]
name = "peacher_sdk"
version = "0.1.0"
edition = "2024"


[features]
utoipa = ["dep:utoipa"]
cli = ["dep:clap", "dep:toml", "dep:dirs", "dep:dialoguer"]
geo = ["dep:geo", "dep:geojson"]

[dependencies]
peanut.workspace = true
serde.workspace = true
geo = { workspace = true, optional = true }
geojson = {workspace = true, optional = true }
url.workspace = true
ahash.workspace = true
chrono.workspace = true
utoipa = { workspace = true, optional = true }
serde_qs.workspace = true
tracing.workspace = true
clap = { workspace = true, optional = true, features = ["derive"] }
anyhow = { workspace = true }
reqwest = { workspace = true }
toml = { workspace = true, optional = true }
dirs = { workspace = true, optional = true }
dialoguer = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true
strum.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
tokio = { workspace = true, features = ["full"] }
